= Certificacion electronica cocumentos

image:https://github.com/alexjcm/certificacion-electronica-docs/actions/workflows/main.yml/badge.svg["Build and testing", link="https://github.com/alexjcm/certificacion-electronica-docs/actions/workflows/main.yml"]
image:https://img.shields.io/badge/License-GPLv3-blue.svg[License: GPL v3, https://www.gnu.org/licenses/gpl-3.0] 

Servicio web REST para recibir documentos firmados digitalmente por el servicio de Firma Digital (firmadigital-servicio).

== Prerrequisitos

- JDK 11.- Para compilar y ejecutar la aplicación.

- WildFly 33.- Para desplegar la aplicación se necesita un servidor de aplicaciones *Jakarta EE 10* disponible en http://www.wildfly.org[wildfly.org]

- Maven 3.- Para compilar y empaquetar se utiliza http://maven.apache.org[Apache Maven].


== Cómo compilar

Para compilar se debe utilizar Apache Maven:

[source, bash]
----
mvn clean package
----

== Cómo desplegar

Se debe copiar el archivo `target/recepcion.war` a la carpeta `standalone/deployments` de un servidor de aplicaciones WildFly 29.

== Desarrollo

Para probar el servicio web se puede ejecutar los siguientes comandos desde consola:

[source,bash]
----
export URL_SERVICIO="http://localhost:7776/recepcion/receiveDocument/saveSignedFile"  &&
export BASE64=`base64 -w0 /home/<your-user>/Descargas/documento-ejemplo.pdf`   &&
export JSON="{\"nombreDocumento\":\"documento-ejemplo.pdf\",\"archivo\":\"${BASE64}\"}"         &&
export RESPUESTA=`curl -s -H "Content-Type: application/json" -X POST -d "${JSON}" ${URL_SERVICIO}`  &&  
echo $RESPUESTA
----


Luego, enviamos la ruta absoluta del archivo generado anteriormente para probar el servicio:

[source,bash]
----
export URL_SERVICIO="http://localhost:7776/recepcion/receiveDocument/checkSignedFileExists?location="   &&
export RUTA_DOC_A_VERIFICAR="/opt/wildfly-static/documento-ejemplo.pdf"   &&
export URL_FINAL=${URL_SERVICIO}${RUTA_DOC_A_VERIFICAR}
export RESPUESTA=`curl -s -H "Content-Type: application/json" -X GET ${URL_FINAL}`  &&  
echo $RESPUESTA
----


También se puede enviar la url del archivo generado anteriormente para probar el servicio:

[source,bash]
----
export URL_SERVICIO="http://localhost:7776/recepcion/receiveDocument/checkSignedFileExists?location="   &&
export URL_DOC_A_VERIFICAR="http://localhost:7776/certificado1.pdf"   &&
export URL_FINAL=${URL_SERVICIO}${RUTA_DOC_A_VERIFICAR}
export RESPUESTA=`curl -s -H "Content-Type: application/json" -X GET ${URL_FINAL}`  &&  
echo $RESPUESTA
----


== Versiones

Usamos http://semver.org[SemVer] para versionar.


== Documentación

https://alexjcm.github.io/certificacion-electronica-docs[Ver documentación]


== Licencia

Este proyecto está licenciado bajo la licencia GPL v3. Revise el archivo link:LICENSE[LICENSE] para más detalles.
