= certificacion-electronica-docs
Servicio web REST para recibir documentos firmados digitalmente.

== Cómo compilar

Para compilar se debe utilizar Apache Maven:

----
mvn clean package
----

== Cómo desplegar

Se debe copiar el archivo `target/recepcion.war` a la carpeta `standalone/deployments` de un servidor de aplicaciones WildFly 20.

== Desarrollo

Para probar el servicio web ejecutamos los siguientes comandos desde consola:
[source,bash]
----
export DIR_PDFS='/home/alexjcm/Descargas/firmaec-original-v2.8.1/z_pdfs-para-probar-firmado'  &&
export URL_SERVICIO="http://localhost:8180/recepcion/rest"  &&
export BASE64=`base64 -w0 ${DIR_PDFS}/certificado1.pdf`   &&
export JSON="{\"nombreDocumento\":\"certificado1.pdf\",\"archivo\":\"${BASE64}\"}"         &&
export RESPUESTA=`curl -s -H "Content-Type: application/json" -X POST -d "${JSON}" ${URL_SERVICIO}`  &&  
echo $RESPUESTA
----


Luego, enviamos la ruta del archivo generado anteriormente para probar el servicio:
[source,bash]
----
export URL_SERVICIO="http://localhost:8180/recepcion/rest?dirpdf="   &&
export RUTA_DOC_A_VERIFICAR="/opt/wildfly-static/certificado1.pdf"   &&
export URL_FINAL=${URL_SERVICIO}${RUTA_DOC_A_VERIFICAR}
export RESPUESTA=`curl -s -H "Content-Type: application/json" -X GET ${URL_FINAL}`  &&  
echo $RESPUESTA
----


También se puede enviar la url del archivo generado anteriormente para probar el servicio:
[source,bash]
----
export URL_SERVICIO="http://localhost:8180/recepcion/rest?dirpdf="   &&
export URL_DOC_A_VERIFICAR="http://localhost:8180/certificado1.pdf"   &&
export URL_FINAL=${URL_SERVICIO}${RUTA_DOC_A_VERIFICAR}
export RESPUESTA=`curl -s -H "Content-Type: application/json" -X GET ${URL_FINAL}`  &&  
echo $RESPUESTA
----


== Construido con

* https://maven.apache.org/[Maven] - Dependency Management


== Versiones

Usamos http://semver.org[SemVer] para versionar.


== Licencia

Este proyecto está licenciado bajo la licencia AGPL v3.
Revisar LICENSE para detalles.
