= certificacion-electronica-docs

image:https://travis-ci.com/AlexJCM/certificacion-electronica-docs.svg?branch=main["Build Status", link="https://travis-ci.com/AlexJCM/certificacion-electronica-docs"]
image:https://img.shields.io/badge/License-GPLv3-blue.svg[License: GPL v3, https://www.gnu.org/licenses/gpl-3.0] 

Servicio web REST para recibir documentos firmados digitalmente.

== Prerrequisitos

-  http://www.oracle.com/technetwork/java/javase/downloads/[Java 8] - para compilar y ejecutar la aplicación
- https://maven.apache.org/[Maven] - Dependency Management.


== Cómo compilar

Para compilar se debe utilizar Apache Maven:

----
mvn clean package
----

== Cómo desplegar

Se debe copiar el archivo `target/recepcion.war` a la carpeta `standalone/deployments` de un servidor de aplicaciones WildFly 20.

== Desarrollo

Para probar el servicio web se puede ejecutar los siguientes comandos desde consola:
[source,bash]
----
export URL_SERVICIO="http://localhost:8180/recepcion/rest"  &&
export BASE64=`base64 -w0 /home/<your-user>/Descargas/documento-ejemplo.pdf`   &&
export JSON="{\"nombreDocumento\":\"documento-ejemplo.pdf\",\"archivo\":\"${BASE64}\"}"         &&
export RESPUESTA=`curl -s -H "Content-Type: application/json" -X POST -d "${JSON}" ${URL_SERVICIO}`  &&  
echo $RESPUESTA
----


Luego, enviamos la ruta absoluta del archivo generado anteriormente para probar el servicio:
[source,bash]
----
export URL_SERVICIO="http://localhost:8180/recepcion/rest?dirpdf="   &&
export RUTA_DOC_A_VERIFICAR="/opt/wildfly-static/documento-ejemplo.pdf"   &&
export URL_FINAL=${URL_SERVICIO}${RUTA_DOC_A_VERIFICAR}
export RESPUESTA=`curl -s -H "Content-Type: application/json" -X GET ${URL_FINAL}`  &&  
echo $RESPUESTA
----


También se puede enviar la url del archivo generado anteriormente para probar el servicio:
[source,bash]
----
export URL_SERVICIO="http://localhost:8180/recepcion/rest?dirpdf="   &&
export URL_DOC_A_VERIFICAR="http://localhost:8180/certificado1.pdf"   &&
export URL_FINAL=${URL_SERVICIO}${RUTA_DOC_A_VERIFICAR}
export RESPUESTA=`curl -s -H "Content-Type: application/json" -X GET ${URL_FINAL}`  &&  
echo $RESPUESTA
----


== Versiones

Usamos http://semver.org[SemVer] para versionar.


== Documentación

Ver documentación en: https://alexjcm.github.io/certificacion-electronica-docs


== Licencia

Este proyecto está licenciado bajo la licencia GPL v3. Revise el archivo <<LICENSE, LICENSE>> para más detalles.
